name: mentionable_text_field
description: A flutter text field that has a mention feature
version: 0.0.1
homepage: https://github.com/AlexisDeslandes/mentionable_text_field

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  
flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: